<?php

namespace Tests;

use Tests\TestCase;
use Voronoi\Apprentice\Libraries\QRCode;

class QRCodeTest extends TestCase
{
    public function testOutput()
    {
        $qrCode = new QRCode;
        $qrCode->setBackColor("X");
        $qrCode->setForeColor("O");

        $output = $qrCode->terminal('hello world');

        $expected =
"OOOOOOOOOOOOOOOOOOOOOOOOOOO
OXXXXXXXOXOOXXOXXXOXXXXXXXO
OXOOOOOXOXOOXOXOXOOXOOOOOXO
OXOXXXOXOXXXXOXOOXOXOXXXOXO
OXOXXXOXOOXOXOOXOOOXOXXXOXO
OXOXXXOXOOXOXXXOOXOXOXXXOXO
OXOOOOOXOXXOXXOOOOOXOOOOOXO
OXXXXXXXOXOXOXOXOXOXXXXXXXO
OOOOOOOOOXOXXXOOOXOOOOOOOOO
OOOXXXOXOXXXOOXOOOXXXOOXXXO
OOXOOXXOXOOOOXXXXXXOXXOOOXO
OOXXOOOXXXOXOXOOXXXXOXXXOOO
OOXOOOOOXXXOOXOXXOXOXOOOOOO
OOOOOOXXOXXXXOOXXOOXXXOOXXO
OXXOOOOOXOOOXOOOXXOOXOOOXOO
OXOOOXXXOOXXXXOXOOXXXXXXOOO
OXOXOOOOOOXOOXXXOXOOXOOXOXO
OXOXXXXXOXXOOXOXOXXXXXXOOXO
OOOOOOOOOXXXXOOXXXOOOXOOOXO
OXXXXXXXOOOOXXOXXXOXOXXXXXO
OXOOOOOXOOXOXOOOXXOOOXOXOOO
OXOXXXOXOXXOOOXXXXXXXXXOOOO
OXOXXXOXOXXOOXXXXOXOOOOOXXO
OXOXXXOXOXOXOOXXXOOXOOXXOXO
OXOOOOOXOOOXXOOXXOXXOXOXXOO
OXXXXXXXOOXOXOOXOOOOOOOXXXO
OOOOOOOOOOOOOOOOOOOOOOOOOOO\n";

        $this->assertEquals($expected, $output);
    }
}
